# Generated by Django 3.2.4 on 2021-07-01 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCode',
            new_name='state',
        ),
    ]
