# Generated by Django 3.2.4 on 2021-07-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210701_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
