# Generated by Django 3.2.4 on 2021-07-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isOrdered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isShipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shippedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
