# Generated by Django 3.2.4 on 2021-07-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210704_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isOrdered',
            new_name='isPacked',
        ),
    ]
