# Generated by Django 3.2.4 on 2021-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
