products = [
    {
        '_id': '1',
        'name': 'Fortune Mustard Oil',
        'image': '/images/fortune_mustard_oil.webp',
        'description': 'Pure Kachhi Ghani Oil.Healthy for all ages',
        'brand': 'Fortune',
        'category': 'Oil',
        'price': 205.00,
        'countInStock': 25,
        'rating': 4.5,
        'numReviews': 10,
    },
    {
        '_id': '2',
        'name': 'Maggie Noodles',
        'image': '/images/maggie.jpg',
        'description': 'Made with wheat.Can be cook easily within 5 minutes',
        'brand': 'Maggie',
        'category': 'Food',
        'price': 12.00,
        'countInStock': 0,
        'rating': 4.2,
        'numReviews': 13,
    },
    {
        '_id': '3',
        'name': 'Ashrivad Chakki Atta',
        'image': '/images/ashrivad_atta.jpeg',
        'description': 'Atta contains 0% wheat.Available in affordable price',
        'brand': 'Ashrivad',
        'category': 'Food',
        'price': 45.00,
        'countInStock': 13,
        'rating': 4.3,
        'numReviews': 21,
    },
    {
        '_id': '4',
        'name': 'Nivea Shower gel',
        'image': '/images/nivea_shower_gel.jpg',
        'description': 'Shower gel with moistureizer.It can protect skin from rashes',
        'brand': 'Nivea',
        'category': 'Skin Product',
        'price': 136.00,
        'countInStock': 9,
        'rating': 4.6,
        'numReviews': 34,
    },
    {
        '_id': '5',
        'name': 'Gooday Cookies',
        'image': '/images/goodday_cookies.jpg',
        'description': 'Cookies with Chocolate dot on it',
        'brand': 'Goodday',
        'category': 'Food',
        'price': 10,
        'countInStock': 49,
        'rating': 4.1,
        'numReviews': 14,
    },
]